language: c

compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
 #Quick fix using one subversion previous
  - wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-2/CUnit-2.1-2-src.tar.bz2
  - tar -xvjpf CUnit-2.1-2-src.tar.bz2
  - cd CUnit-2.1-2
  - mkdir -p $HOME/local
  - ./configure –prefix=$HOME/local
  - make clean
  - make
  - make install
  - export C_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$C_INCLUDE_PATH
  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
  #Come back to the repo unwarpped folder
  - cd ..
  
install:
  - echo  "Reached Install Section"

script:
  - echo "Reached Script Section"
  - gcc  SourceCode/main.c  SourceCode/Calculator.c -o Calculator
  - ./Calculator
  - ls
  #- cd $HOME/local
  - echo "Reached Script Section - Unit_Test"
  - gcc -Wall -I$HOME/local/include Unit_Test.c -L$HOME/local/lib -lcunit -o Unit_Test
  - ./Unit_Test
